package com.roshka.dtos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

// Generated by https://quicktype.io
@JsonIgnoreProperties(ignoreUnknown = true)
@XmlAccessorType(XmlAccessType.FIELD)
public class NoticiaDto {
    private String fecha;
    private String enlace;
    @JsonProperty("enlace_foto")
    private String enlaceFoto;
    private String titulo;
    private String resumen;
    @JsonProperty("contenido_foto")
    private String contenidoFoto;
    @JsonProperty("content_type_foto")
    private String contentTypeFoto;

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String value) {
        this.fecha = value;
    }

    public String getEnlace() {
        return enlace;
    }

    public void setEnlace(String value) {
        this.enlace = value;
    }

    public String getEnlaceFoto() {
        return enlaceFoto;
    }

    public void setEnlaceFoto(String value) {
        this.enlaceFoto = value;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String value) {
        this.titulo = value;
    }

    public String getResumen() {
        return resumen;
    }

    public void setResumen(String value) {
        this.resumen = value;
    }

    public String getContenidoFoto() {
        return contenidoFoto;
    }

    public void setContenidoFoto(String contenidoFoto) {
        this.contenidoFoto = contenidoFoto;
    }

    public String getContentTypeFoto() {
        return contentTypeFoto;
    }

    public void setContentTypeFoto(String contentTypeFoto) {
        this.contentTypeFoto = contentTypeFoto;
    }

    @Override
    public String toString() {
        return "NoticiaDto [contenidoFoto=" + contenidoFoto + ", contentTypeFoto=" + contentTypeFoto + ", enlace="
                + enlace + ", enlaceFoto=" + enlaceFoto + ", fecha=" + fecha + ", resumen=" + resumen + ", titulo="
                + titulo + "]";
    }

}
