package com.roshka.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

// Generated by https://quicktype.io
@JsonIgnoreProperties(ignoreUnknown = true)
@XmlAccessorType(XmlAccessType.FIELD)
public class NoticiaDto {
    private String fecha;
    private String enlace;
    @JsonProperty("enlace_foto")
    private String enlaceFoto;
    private String titulo;
    private String resumen;

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String value) {
        this.fecha = value;
    }

    public String getEnlace() {
        return enlace;
    }

    public void setEnlace(String value) {
        this.enlace = value;
    }

    public String getEnlaceFoto() {
        return enlaceFoto;
    }

    public void setEnlaceFoto(String value) {
        this.enlaceFoto = value;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String value) {
        this.titulo = value;
    }

    public String getResumen() {
        return resumen;
    }

    public void setResumen(String value) {
        this.resumen = value;
    }

    @Override
    public String toString() {
        return "NoticiaDto [enlace=" + enlace + ", enlaceFoto=" + enlaceFoto + ", fecha=" + fecha + ", resumen="
                + resumen + ", titulo=" + titulo + "]";
    }

    
}
