package com.roshka.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

// Generated by https://quicktype.io
@JsonIgnoreProperties(ignoreUnknown = true)
public class NoticiaDto {
    private String fecha;
    private String enlace;
    @JsonProperty("enlace_foto")
    private String enlaceFoto;
    private String titulo;
    private String resumen;

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String value) {
        this.fecha = value;
    }

    public String getEnlace() {
        return enlace;
    }

    public void setEnlace(String value) {
        this.enlace = value;
    }

    public String getEnlaceFoto() {
        return enlaceFoto;
    }

    public void setEnlaceFoto(String value) {
        this.enlaceFoto = value;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String value) {
        this.titulo = value;
    }

    public String getResumen() {
        return resumen;
    }

    public void setResumen(String value) {
        this.resumen = value;
    }
}
